function ma = get_ma_vector(%m_i, ... % these are the examples of the possible input
        % ri ... % Only include the inputs that are necessary
        % theta_i ...
        % dtheta_i ...
        % ddtheta_i ...
        % ddr_i, ...
        % I_Gi);

% ENTER YOUR CODE HERE %

ma = [ % mi * a_g_ix; ...
       % mi * a_g_iy; ... etc
       % ENTER YOUR CODE HERE %
    ];

end